### ISSUE TITLE
hash routing for client-side only apps

### ISSUE THREAD

**Issue by peter-mouland** [developit/preact-router#88] opened 2016-09-29 23:39 UTC
hey, I was just giving this a try and doing the _standard_ comparison with react and couldn't get the hashHistory (https://github.com/developit/preact-router/pull/60) to work.

You can see the code I've used here : https://github.com/peter-mouland/react-lego/compare/master...preact

Any idea what i'm missing?

ps, love how simple it was to do the swap from React!

**Comment by developit** [comment] 2016-10-21 22:53
As far as I know, yeah.  I think support for custom history had actually just not been published yet when you tested it out! 😳

**Comment by peter-mouland** [comment] 2016-10-22 14:14
I've just tried it again an didn't have any luck.

In the repo (https://github.com/peter-mouland/react-lego/tree/preact), clicking a top level link will take me to `http://localhost:8080/#/game/` for example.  I'd hope that refreshing the page would then re-load the correct route, but i this isn't happening.

**Comment by Wykks** [comment] 2016-11-03 22:48
Hi !
I'm not able to make it work too
https://github.com/Wykks/Untamed-Now-Playing-Next/commit/cc4115375366e8b76a6a758b9eea9275c2bf214c#diff-6837e7aa0437e52bdfb1ee19a42b2b24
My link simply doesn't work, any idea ?

**Comment by developit** [comment] 2016-11-04 02:27
@Wykks Despite using hash history, I believe you'd currently need to omit the hash from your links. `<a href="/foo" />` gets hooked by the router and navigates to `#/foo`.

**Comment by peter-mouland** [comment] 2016-11-04 07:45
indeed - my links are working, you can see here, my link helper doesn't use # : https://github.com/peter-mouland/react-lego/blob/preact/src/app/routes.js#L15-L35, but when you click, the hash is automatically added.  

my problem is then if the pages is refreshed, the app doesn't know where it is and just loads the index.

**Comment by Wykks** [comment] 2016-11-04 18:22
Indeed, my bad, thanks :+1: .

However I have the same issue as peter when refreshing the page

**Comment by developit** [comment] 2016-11-05 01:43
Kk, I think it's something I can fix quickly, just I've never actually used hashHistory haha

**Comment by iamale** [comment] 2016-11-07 01:02
@developit I think the problem is the hash- and memoryHistory implementations do not have the `getCurrentLocation` [you are expecting from them](https://github.com/developit/preact-router/blob/0d6e2c14349fe42f3cd7d4d40239e4284ec7981b/src/index.js#L19-L21).

I'm using a `history.getCurrentLocation = () => history.location;` monkey patch as a quick fix for this.

**Comment by developit** [comment] 2016-11-07 01:03
oh... why don't they have that method? Seems very strange... 🙍

**Comment by iamale** [comment] 2016-11-07 01:08
Seems it was removed in 4.0.0 (released on September, 9th), so... _shrugs_

**Comment by iamale** [comment] 2016-11-07 01:09
(Changelog: https://github.com/mjackson/history/blob/e4434544b8bc621e0cbdeafa6938a6e77b922dd8/CHANGES.md#v400-2)

**Comment by developit** [comment] 2016-11-07 01:29
Ah - maybe the intent is to have people use `.location`. I'll try adding that as a fallback.

**Closed** 2016-11-07 01:31 UTC

**Comment by developit** [comment] 2016-11-07 01:33
Fix for initial location released as [2.3.1](https://github.com/developit/preact-router/releases/tag/2.3.1)!

**Comment by peter-mouland** [comment] 2016-11-10 20:02
Awesome - update worked in my app without a single code change. cheers

**Comment by developit** [comment] 2016-11-10 20:03
Yay!! 😍
