### ISSUE TITLE
Typescript router type property problem

### ISSUE THREAD

**Issue by davutkara** [developit/preact-router#283] opened 2018-05-16 09:30 UTC
![image](https://user-images.githubusercontent.com/10008440/40108860-ca82dae0-5904-11e8-9b79-4ae5dc0b0850.png)

`app/react/first.tsx(14,10): error TS2339: Property 'path' does not exist on type '{}'.
app/react/first.tsx(15,13): error TS2322: Type '{ path: string; }' is not assignable to type 'user'.
  Property 'user' is missing in type '{ path: string; }'.
app/react/first.tsx(16,11): error TS2322: Type '{ type: string; default: true; }' is not assignable to type 'route'.
  Property 'url' is missing in type '{ type: string; default: true; }'.
app/react/first.tsx(35,20): error TS2304: Cannot find name 'Component'.
app/react/first.tsx(37,8): error TS2339: Property 'setState' does not exist on type 'Home'.`

**Comment by Alexendoo** [comment] 2018-05-21 13:53
Duplicate of #280

**Closed by Alexendoo** 2018-05-21 13:53 UTC

**Comment by giuseppelt** [comment] 2023-07-26 13:22
In your `env.d.ts`

```ts
namespace preact {
    namespace JSX {
        interface IntrinsicAttributes {
            path?: string
        }
    }
}
```
Enjoy : )
